name: github-actions
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the workflow
      run: |
        set -x
        # Run the script
        npm install
        cd test
        npm install
        # Use own PAT to avoid some API endpoints being unavailable to integration tokens
        node . ${{secrets.GITHUB_PAT}}
