name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the main branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Configure Git for the push from the workflow to the repository
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Install Node dependencies
      run: npm install
    - name: Run the tests
      run: node test
    - name: Generate the declaration file
      run: npx tsc index.js --allowJs --declaration --emitDeclarationOnly
    - name: Append time stamp to ensure Git change
      run: echo "// $(date)" >> index.d.ts
    - name: Stage the Git index changes resulting from the CI script
      run: git add index.d.ts
    - name: Reset unstaged changes so that Git commit won't fail (e.g. package-lock.json, temporary files, …)
      run: git checkout -- .
    - name: Commit the staged changes to the workflow repository
      run: git commit -m "Commit generated documentation"
    - name: Rebase if the branch has changed meanwhile or fail on automatically irresolvable conflicts
      run: git pull --rebase
    - name: Push the commit to the workflow repository
      run: git push
